# Generated by Django 3.1.7 on 2021-03-16 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feshion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 16, 6, 6, 11, 98299, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
