# Generated by Django 3.1.7 on 2021-03-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feshion', '0002_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='num_visits',
            field=models.IntegerField(default=0),
        ),
    ]
